import { $, addNewKeyValueToForm, getFormDataAsObject, addParamsToURL, showAddItemModal } from './_functions'

export default function App() {
  // Get the form element
  const form = $('#form')

  // Stop if no form is found
  if (!form) {
    return
  }

  // Get the Add Parameter HTML button inside the form element
  const addParameterButton = $('#add-parameter-button', form)

  // This is the initial input count which tracks how many query parameters have been created
  // We increment this by 1 every time a new key/value group is created
  // Every key:input will have the name as key-# and value-#
  let inputCount = 0

  form.addEventListener('submit', e => {
    e.preventDefault()

    // Returns all the input values of the form as an object
    const formData = getFormDataAsObject(form)

    const url = formData?.url || ''

    if (!url) {
      // alert('You must enter a valid URL (e.g. https://www.example.com)')
      e.target.elements.url.focus()
      return
    }

    // All optional params will be pushed into this object {key-#:value,key-#:value}
    const params = {}

    // Loop through keys to find "key-X" and "value-X" pairs
    // This loop is generated by ChatGPT
    for (let i = 1; formData[`key-${i}`] && formData[`value-${i}`]; i++) {
      params[formData[`key-${i}`]] = formData[`value-${i}`]
    }

    // Create the URL with the query parameters attached to it
    const finalurl = addParamsToURL(url, params)

    if (!finalurl) {
      return
    }

    // Show modal so the user can copy the URL
    showAddItemModal(finalurl)
  })

  addParameterButton.addEventListener('click', () => {
    // Increment so every key/value group can be matched easily
    inputCount++

    // Add a new key/value input group to the DOM
    addNewKeyValueToForm(inputCount)
  })
}
